
export const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING'

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'

export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const AUTHENTICATION = 'AUTHTENTICATION'

export const FETCH_USERS = 'FETCH_USERS'

export const ADD_USER_PENDING = 'ADD_USER_PENDING'

export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'

export const ADD_USER_ERROR = 'ADD_USER_ERROR'

export const USER_LOGOUT = 'USER_LOGOUT'

//
export const FETCH_STUDENT = 'FETCH_STUDENT'
export const ADD_STUDENT_PENDING = 'ADD_STUDENT_PENDING'
export const ADD_STUDENT_SUCCESS = 'ADD_STUDENT_SUCCESS'
export const ADD_STUDENT_ERROR = 'ADD_STUDENT_ERROR'

export const DELETE_STUDENT_PENDING = 'DELETE_STUDENT_PENDING'

export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS'

export const DELETE_STUDENT_ERROR = 'DELETE_STUDENT_ERROR'


export const UPDATE_STUDENT_PENDING = 'UPDATE_STUDENT_PENDING'

export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS'

export const UPDATE_STUDENT_ERROR = 'UPDATE_STUDENT_ERROR'

export const SET_SELECTED_STUDENT_ID = 'SET_SELECTED_STUDENT_ID'  
