
export const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING'

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'

export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const IS_AUTH = 'IS_AUTH'

export const FETCH_USERS = 'FETCH_USERS'

export const ADD_USER_PENDING = 'ADD_USER_PENDING'

export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'

export const ADD_USER_ERROR = 'ADD_USER_ERROR'

export const USER_LOGOUT = 'USER_LOGOUT'

//
export const FETCH_STUDENTS = 'FETCH_STUDENTS'
export const ADD_STUDENTS_PENDING = 'ADD_STUDENT_PENDING'
export const ADD_STUDENTS_SUCCESS = 'ADD_STUDENT_SUCCESS'
export const ADD_STUDENTS_ERROR = 'ADD_STUDENT_ERROR'

export const DELETE_STUDENTS_PENDING = 'DELETE_STUDENTS_PENDING'

export const DELETE_STUDENTS_SUCCESS = 'DELETE_STUDENTS_SUCCESS'

export const DELETE_STUDENTS_ERROR = 'DELETE_STUDENTS_ERROR'


export const UPDATE_STUDENTS_PENDING = 'UPDATE_STUDENTS_PENDING'

export const UPDATE_STUDENTS_SUCCESS = 'UPDATE_STUDENTS_SUCCESS'

export const UPDATE_STUDENTS_ERROR = 'UPDATE_STUDENTS_ERROR'

export const SET_SELECTED_STUDENTS_ID = 'SET_SELECTED_STUDENTS_ID'  
